program pVenda;

// mCreateEnt

uses
  Forms,
  mEdit,
  mComboBox,
  mCheckBox,
  mCheckListBox,
  mListBox,
  mListView,
  mFrame,
  mForm,
  mProperty,
  mObjetoJson,
  mTempoString,
  mAppException,
  mAppMessage,
  mAppSerial,
  mCollection,
  mCollectionItem,
  mCollectionMap,
  mCollectionSet,
  mField,
  mFieldControl,
  mTipoCampo,
  mTipoEstilo,
  mTipoMensagem,
  mTipoParametro,
  uTipoDocumentoFiscal in 'model\uTipoDocumentoFiscal.pas',
  uTipoImposto in 'model\uTipoImposto.pas',
  uTipoImpressaoDanfe in 'model\uTipoImpressaoDanfe.pas',
  uTipoModalidade in 'model\uTipoModalidade.pas',
  uTipoOperacao in 'model\uTipoOperacao.pas',
  uTipoProcessamento in 'model\uTipoProcessamento.pas',
  uTipoRetornoSefaz in 'model\uTipoRetornoSefaz.pas',
  uAliqicms in 'model\uAliqicms.pas',
  uCaixa in 'model\uCaixa.pas',
  uCfop in 'model\uCfop.pas',
  uEmpresa in 'model\uEmpresa.pas',
  uEquip in 'model\uEquip.pas',
  uEstado in 'model\uEstado.pas',
  uHistrel in 'model\uHistrel.pas',
  uMunicipio in 'model\uMunicipio.pas',
  uNcm in 'model\uNcm.pas',
  uNcmsubst in 'model\uNcmsubst.pas',
  uOperacao in 'model\uOperacao.pas',
  uPagto in 'model\uPagto.pas',
  uPagtoparc in 'model\uPagtoparc.pas',
  uPais in 'model\uPais.pas',
  uPessoa in 'model\uPessoa.pas',
  uProduto in 'model\uProduto.pas',
  uRegrafiscal in 'model\uRegrafiscal.pas',
  uRegrafiscalimposto in 'model\uRegrafiscalimposto.pas',
  uTransacao in 'model\uTransacao.pas',
  uTransdfe in 'model\uTransdfe.pas',
  uTransfiscal in 'model\uTransfiscal.pas',
  uTransimposto in 'model\uTransimposto.pas',
  uTransitem in 'model\uTransitem.pas',
  uTranspagto in 'model\uTranspagto.pas',
  uTransvencto in 'model\uTransvencto.pas',
  uUsuario in 'model\uUsuario.pas',
  uAliqicmsMap in 'repositorio\mapping\uAliqicmsMap.pas',
  uCaixaMap in 'repositorio\mapping\uCaixaMap.pas',
  uCfopMap in 'repositorio\mapping\uCfopMap.pas',
  uEmpresaMap in 'repositorio\mapping\uEmpresaMap.pas',
  uEquipMap in 'repositorio\mapping\uEquipMap.pas',
  uEstadoMap in 'repositorio\mapping\uEstadoMap.pas',
  uHistrelMap in 'repositorio\mapping\uHistrelMap.pas',
  uMunicipioMap in 'repositorio\mapping\uMunicipioMap.pas',
  uNcmMap in 'repositorio\mapping\uNcmMap.pas',
  uNcmsubstMap in 'repositorio\mapping\uNcmsubstMap.pas',
  uOperacaoMap in 'repositorio\mapping\uOperacaoMap.pas',
  uPagtoMap in 'repositorio\mapping\uPagtoMap.pas',
  uPagtoparcMap in 'repositorio\mapping\uPagtoparcMap.pas',
  uPaisMap in 'repositorio\mapping\uPaisMap.pas',
  uPessoaMap in 'repositorio\mapping\uPessoaMap.pas',
  uProdutoMap in 'repositorio\mapping\uProdutoMap.pas',
  uRegrafiscalMap in 'repositorio\mapping\uRegrafiscalMap.pas',
  uRegrafiscalImpostoMap in 'repositorio\mapping\uRegrafiscalImpostoMap.pas',
  uTransacaoMap in 'repositorio\mapping\uTransacaoMap.pas',
  uTransdfeMap in 'repositorio\mapping\uTransdfeMap.pas',
  uTransfiscalMap in 'repositorio\mapping\uTransfiscalMap.pas',
  uTransimpostoMap in 'repositorio\mapping\uTransimpostoMap.pas',
  uTransitemMap in 'repositorio\mapping\uTransitemMap.pas',
  uTranspagtoMap in 'repositorio\mapping\uTranspagtoMap.pas',
  uTransvenctoMap in 'repositorio\mapping\uTransvenctoMap.pas',
  uUsuarioMap in 'repositorio\mapping\uUsuarioMap.pas',
  uclsCaixaServico in 'servico\uclsCaixaServico.pas',
  uclsContingenciaServico in 'servico\uclsContingenciaServico.pas',
  uclsDFeServico in 'servico\uclsDFeServico.pas',
  uclsEmpresaServico in 'servico\uclsEmpresaServico.pas',
  uclsEquipServico in 'servico\uclsEquipServico.pas',
  uclsImpostoServico in 'servico\uclsImpostoServico.pas',
  uclsOperacaoServico in 'servico\uclsOperacaoServico.pas',
  uclsPagamentoServico in 'servico\uclsPagamentoServico.pas',
  uclsPessoaServico in 'servico\uclsPessoaServico.pas',
  uclsProdutoServico in 'servico\uclsProdutoServico.pas',
  uclsRegrafiscalServico in 'servico\uclsRegrafiscalServico.pas',
  uclsTransacaoServico in 'servico\uclsTransacaoServico.pas',
  uclsUsuarioServico in 'servico\uclsUsuarioServico.pas',
  uclsContexto in 'repositorio\uclsContexto.pas',
  uclsMapeamento in 'repositorio\uclsMapeamento.pas',
  uclsMigracao in 'repositorio\uclsMigracao.pas',
  uclsPopulador in 'repositorio\uclsPopulador.pas',
  uclsAliqicmsPopulador in 'repositorio\populador\uclsAliqicmsPopulador.pas',
  uclsCfopPopulador in 'repositorio\populador\uclsCfopPopulador.pas',
  uclsEstadoPopulador in 'repositorio\populador\uclsEstadoPopulador.pas',
  uclsMunicipioPopulador in 'repositorio\populador\uclsMunicipioPopulador.pas',
  uclsNcmPopulador in 'repositorio\populador\uclsNcmPopulador.pas',
  uclsOperacaoPopulador in 'repositorio\populador\uclsOperacaoPopulador.pas',
  uclsPaisPopulador in 'repositorio\populador\uclsPaisPopulador.pas',
  uclsRegrafiscalPopulador in 'repositorio\populador\uclsRegrafiscalPopulador.pas',
  uclsTestar in 'view\uclsTestar.pas',
  ufrmVenda in 'view\ufrmVenda.pas' {F_Venda},
  ufrmPagto in 'view\ufrmPagto.pas' {F_Pagto};

{$R *.res}

begin
  Application.Initialize;
  uclsContexto.Instance;
  TF_Venda.Execute();
  Application.Run;
end.
